# Web Server
server.port=${PORT:9091}
server.address=0.0.0.0
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Essential Postgres Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection variables that match your Render Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=false
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://net-shield-gules.vercel.app,http://localhost:3000,http://localhost:8080}
